mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    - hyde.ext.plugins.meta.SorterPlugin
    - hyde.ext.plugins.meta.TaggerPlugin
    - hyde.ext.plugins.text.SyntextPlugin
    - hyde.ext.plugins.text.TextlinksPlugin
context:
    data:
        site_title: OSILLA
        author:
            name: Osilla
            url: "http://osilla.github.io"
        google_analytics_id: UA-XXXXX-YY
        home_url: index.html
       
